/**
 * apps/api/src/jobs/weeklyLifeTick.ts
 *
 * The Weekly Life Engine. Once a week (queues/weeklyLifeQueue.ts registers
 * the schedule) this iterates every PawBall and appends one `weekly_life`
 * Memory per cat: a short, in-fiction "what they got up to this week" note,
 * generated by modules/lore's `generateWeeklyUpdate` — a real Gemini call
 * per PawBall (modules/lore/lore.gemini.ts), falling back to the seeded
 * 8-variants-per-element template pool if GEMINI_API_KEY is unset or the
 * call fails after retries, so one bad Gemini call can't stall the run for
 * every other cat.
 *
 * This is sequential (`for await`), one Gemini round trip per PawBall —
 * fine at hobby-project collection sizes; a large collection would want to
 * batch/parallelize with a concurrency cap before this becomes the
 * bottleneck.
 *
 * Idempotent: `Memory.weekKey` + its partial unique index mean a re-run for
 * the same week creates nothing new, so a crashed/retried job is safe.
 */

import { Worker, type Job } from "bullmq";
import { getRedisConnection } from "../config/redis";
import {
  generateWeeklyUpdate,
  isoWeekKey,
  isoWeekNumber,
} from "../modules/lore/lore.engine";
import { computeSeed } from "../lib/seededRandom";
import { MemoryModel } from "../models/Memory";
import { PawBallModel } from "../models/PawBall";
import {
  WEEKLY_LIFE_QUEUE_NAME,
  type WeeklyLifeJobData,
} from "../queues/weeklyLifeQueue";

export interface WeeklyLifeResult {
  weekKey: string;
  processed: number;
  created: number;
  skipped: number;
}

export async function runWeeklyLifeTick(
  now: Date = new Date()
): Promise<WeeklyLifeResult> {
  const weekKey = isoWeekKey(now);
  const weekNumber = isoWeekNumber(now);

  let processed = 0;
  let created = 0;
  let skipped = 0;

  const cursor = PawBallModel.find().cursor();
  for await (const pawball of cursor) {
    processed += 1;

    const existing = await MemoryModel.findOne({
      pawballId: pawball._id,
      weekKey,
    })
      .select("_id")
      .lean();
    if (existing) {
      skipped += 1;
      continue;
    }

    const trait = pawball.aura?.traits?.[0] ?? "wandering spirit";
    const text = await generateWeeklyUpdate({
      seed: computeSeed([pawball._id.toString(), "weekly-life"]),
      weekNumber,
      element: pawball.identity.element || "Moon",
      name: pawball.identity.fantasyName || "This cat",
      regionName: pawball.homeRegion?.name || "the wilds",
      trait,
      fantasyClass: pawball.identity.class || "Ranger",
      rarity: pawball.identity.rarity || "common",
      breed: pawball.visualProfile?.breed || "unknown",
    });

    try {
      await MemoryModel.create({
        pawballId: pawball._id,
        ownerId: pawball.ownerId,
        type: "weekly_life",
        text,
        occurredAt: now,
        weekKey,
      });
      created += 1;
    } catch (err) {
      // Partial-unique-index race with a concurrent run — already covered.
      if (isDuplicateKeyError(err)) {
        skipped += 1;
      } else {
        throw err;
      }
    }
  }

  return { weekKey, processed, created, skipped };
}

/** Returns null when REDIS_URL is not configured. The tick itself
 * (`runWeeklyLifeTick`) still works — only the scheduled worker needs Redis. */
export function startWeeklyLifeWorker(): Worker<WeeklyLifeJobData> | null {
  const connection = getRedisConnection();
  if (!connection) return null;

  return new Worker<WeeklyLifeJobData>(
    WEEKLY_LIFE_QUEUE_NAME,
    async (job: Job<WeeklyLifeJobData>) => {
      const asOf = job.data.asOf ? new Date(job.data.asOf) : new Date();
      const result = await runWeeklyLifeTick(asOf);
      // eslint-disable-next-line no-console
      console.log(
        `[weekly-life] ${result.weekKey}: ${result.created} created, ${result.skipped} skipped, ${result.processed} PawBalls`
      );
      return result;
    },
    { connection }
  );
}

function isDuplicateKeyError(err: unknown): boolean {
  return (
    typeof err === "object" &&
    err !== null &&
    "code" in err &&
    (err as { code: unknown }).code === 11000
  );
}
